# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Increment Version
      shell: bash
      run: |
        FN=./Druware.Extensions/Druware.Extensions.csproj
        VERSION=`grep -o -P '<Version>.*</Version>' $FN | sed -n -r "s/^.*<Version>(.*)<\/Version>.*$/\1/p"` 
        MAJOR=`echo $VERSION | awk '{split($0,a,"."); print a[1]}'`
        MINOR=`echo $VERSION | awk '{split($0,a,"."); print a[2]}'`
        REVISION=`echo $VERSION | awk '{split($0,a,"."); print a[3]}'`
        REVISION=$((REVISION+1))
        VERSION=$MAJOR.$MINOR.$REVISION
        sed -r -i '' -e "s/^(.*)<Version>(.*)<\/Version>.*$/\1<Version>$VERSION<\/Version>/g" $FN 
    - name: Build
      run: dotnet build --no-restore --configuration Release 
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --output pub --configuration Release
    #- name: Push to Nuget
    #  shell: bash
    #  run: sh ./Druware.Extensions/nuget-push.sh Druware.Extensions "${{ secrets.NUGET_APIKEY }}"
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "version updated"
        file_pattern: ./Druware.Extensions/Druware.Extensions.csproj

# Remaining to do: commit the updated version number to the repo
# Remaining to do: add a step to create a release tag and push it to the repo
# Remaining to do: add a step to create a release on GitHub
